/*
 * Project Euler 002 - Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <bits/stdc++.h>

using namespace std;

int main(){
    int fibo[100];
    fibo[0] = 1;
    fibo[1] = 2;
    int i = 1;
    int sum = 0;
    while(fibo[i] <= 4000000){
        if(fibo[i]%2 == 0){
            sum += fibo[i];
        }
        i++;
        fibo[i] = fibo[i-1] + fibo[i-2];
    }
    printf("%d", sum);
    return 0;
}
